- name: nginx setup
  hosts: 192.168.33.10
  become: yes
  # define variables
  vars:
    nginx_pgp_url: http://nginx.org/keys/nginx_signing.key
    nginx_repository_url: http://nginx.org/packages/ubuntu/
    conf_file: /etc/nginx/nginx.conf
    default_conf_file: /etc/nginx/conf.d/default.conf
  # define tasks in server.
  tasks:
    - name : Add official nginx PGP key
      apt_key: url={{nginx_pgp_url}} state=present
    - name : Add official nginx repository
      lineinfile : >
        dest=/etc/apt/sources.list
        line='{{item}} {{nginx_repository_url}} {{ansible_distribution_release}} nginx'
      with_items:
        - deb
        - deb-src
    - name : Run apt-get update
      apt: update_cache=yes
    - name : Install nginx
      apt : name=nginx state=present

    - name : copy nginx config file
      template: src=nginx.conf dest={{ conf_file }}

    - name: copy index.html
      template: src=templates/index.html dest=/var/www/html/index.html mode=0644

    - name : Run nginx
      service: name=nginx state=started enabled=yes

    - name: Nginxの起動確認
      shell: ps aux | grep nginx
      register: ps_result
      changed_when: false
